# Compiles Assembly-CSharp without opening Unity, using the Roslyn compiler and the .NET SDK that
# ship inside the Unity Editor install. Useful because Unity's own batch-mode compile refuses to run
# while the Editor has the project open (Temp/UnityLockfile).
#
#   powershell -ExecutionPolicy Bypass -File Tools/compile-check.ps1
#
# Exit code 0 means the project compiles. Errors print as normal CS#### diagnostics.
#
# Reads sources, references, and defines straight out of Assembly-CSharp.csproj, so it stays correct
# as packages come and go. That file is gitignored and regenerated by Unity - if it is missing or
# stale, focus the Editor once to have it rewritten.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$proj = Join-Path $root 'Assembly-CSharp.csproj'

if (-not (Test-Path $proj)) {
    throw "Assembly-CSharp.csproj not found. Open the project in Unity once to generate it."
}

# Match the Editor version the project is pinned to, so the reference assemblies line up.
$versionLine = Select-String -Path (Join-Path $root 'ProjectSettings\ProjectVersion.txt') -Pattern '^m_EditorVersion:\s*(.+)$'
$unityVersion = $versionLine.Matches[0].Groups[1].Value.Trim()

$sdkRoot = "C:\Program Files\Unity\Hub\Editor\$unityVersion\Editor\Data\DotNetSdk"
$dotnet = Join-Path $sdkRoot 'dotnet.exe'
$csc = Get-ChildItem -Path (Join-Path $sdkRoot 'sdk') -Filter 'csc.dll' -Recurse | Select-Object -First 1

if (-not (Test-Path $dotnet)) { throw "dotnet.exe not found under $sdkRoot" }
if (-not $csc) { throw "csc.dll not found under $sdkRoot\sdk" }

[xml]$x = Get-Content $proj

$srcs = @($x.SelectNodes("//*[local-name()='Compile']") | ForEach-Object { $_.GetAttribute('Include') })
$refs = @($x.SelectNodes("//*[local-name()='HintPath']") | ForEach-Object { $_.InnerText })
$defines = ($x.SelectNodes("//*[local-name()='DefineConstants']") | Select-Object -First 1).InnerText

Write-Output "Unity $unityVersion - $($srcs.Count) sources, $($refs.Count) references"

$out = Join-Path $env:TEMP 'gmtk-compile-check.dll'

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('-target:library')
$lines.Add('-langversion:9')
$lines.Add('-nostdlib+')
# CS0649/CS0169/CS0414: [SerializeField] fields are assigned by Unity's serializer, which Roslyn
# cannot see. Suppressed so real diagnostics are not buried.
$lines.Add('-nowarn:0649,0169,0414')
$lines.Add("-out:`"$out`"")
if ($defines) { $lines.Add("-define:$defines") }

foreach ($r in $refs) {
    $p = $r
    if (-not [System.IO.Path]::IsPathRooted($p)) { $p = Join-Path $root $p }
    $lines.Add("-r:`"$p`"")
}
foreach ($s in $srcs) {
    $lines.Add("`"$(Join-Path $root $s)`"")
}

$rsp = Join-Path $env:TEMP 'gmtk-compile-check.rsp'
Set-Content -Path $rsp -Value $lines -Encoding utf8

& $dotnet $csc.FullName "@$rsp"
$code = $LASTEXITCODE

if ($code -eq 0) { Write-Output "COMPILE OK" } else { Write-Output "COMPILE FAILED ($code)" }
exit $code
