# Compiles Assembly-CSharp without opening Unity, using the Roslyn compiler and the .NET SDK that
# ship inside the Unity Editor install. Useful because Unity's own batch-mode compile refuses to run
# while the Editor has the project open (Temp/UnityLockfile).
#
#   powershell -ExecutionPolicy Bypass -File Tools/compile-check.ps1
#
# Exit code 0 means the project compiles. Errors print as normal CS#### diagnostics.
#
# Reads sources, references and defines straight out of Assembly-CSharp.csproj, so it stays correct
# as packages come and go. That file is gitignored and regenerated by Unity - if it is missing,
# focus the Editor once to have it rewritten.
#
# Follows <ProjectReference> nodes recursively (compiling each one first and feeding its output dll
# back in as a -r:), not just <HintPath> ones. Assembly-CSharp reaches Assembly-CSharp-firstpass this
# way - anything under Assets/Plugins (DOTween's Modules/*.cs among them) compiles into that separate
# assembly rather than Assembly-CSharp itself, same reasoning as Assembly-CSharp-Editor reaching
# Assembly-CSharp through a ProjectReference rather than a HintPath. Skipping that reference used to
# make DOTweenModuleUI.cs's extension methods (CanvasGroup.DOFade, RectTransform.DOAnchorPosY, ...)
# invisible here even though Unity itself compiles and runs them fine.
#
# Assets/Editor/** lives in Assembly-CSharp-Editor and is NOT checked by default. Pass -IncludeEditor
# to compile it too:
#
#   powershell -ExecutionPolicy Bypass -File Tools/compile-check.ps1 -IncludeEditor
#
# That path also sweeps in any .cs under Assets/Editor and Assets/Scripts/Editor that the csproj has
# not caught up with yet. The csproj is gitignored and only regenerated when the Unity Editor is
# focused, so a file added since the last focus is otherwise invisible here - which would make the
# check quietly pass on a script it never read.
[CmdletBinding()]
param([switch]$IncludeEditor)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$proj = Join-Path $root 'Assembly-CSharp.csproj'

if (-not (Test-Path $proj)) {
    throw "Assembly-CSharp.csproj not found. Open the project in Unity once to generate it."
}

# Match the Editor version the project is pinned to, so the reference assemblies line up.
$versionLine = Select-String -Path (Join-Path $root 'ProjectSettings\ProjectVersion.txt') -Pattern '^m_EditorVersion:\s*(.+)$'
$unityVersion = $versionLine.Matches[0].Groups[1].Value.Trim()

$sdkRoot = "C:\Program Files\Unity\Hub\Editor\$unityVersion\Editor\Data\DotNetSdk"
$dotnet = Join-Path $sdkRoot 'dotnet.exe'
$csc = Get-ChildItem -Path (Join-Path $sdkRoot 'sdk') -Filter 'csc.dll' -Recurse | Select-Object -First 1

if (-not (Test-Path $dotnet)) { throw "dotnet.exe not found under $sdkRoot" }
if (-not $csc) { throw "csc.dll not found under $sdkRoot\sdk" }

# csprojPath -> built dll path, so a project referenced from more than one place is only compiled
# once. $building guards against a reference cycle turning into infinite recursion.
#
# Compile-Project deliberately returns NOTHING and publishes its result into $built instead. A
# function's return value rides the same success stream that a native command's stdout does, so a
# caller discarding the return value (| Out-Null, $null = ...) also silently discards every compiler
# diagnostic printed underneath it - which is exactly the bug that made this script exit nonzero
# while printing absolutely nothing. Handing the result back out-of-band keeps the success stream
# free for csc's output alone, so no caller ever has a reason to discard it.
$built = @{}
$building = New-Object System.Collections.Generic.HashSet[string]

function Compile-Project([string]$csprojPath, [string[]]$extraSources = @()) {
    $csprojPath = [System.IO.Path]::GetFullPath($csprojPath)

    if ($built.ContainsKey($csprojPath)) { return }

    if (-not $building.Add($csprojPath)) {
        throw "Circular <ProjectReference> involving $csprojPath"
    }

    if (-not (Test-Path $csprojPath)) {
        throw "$csprojPath not found. Open the project in Unity once to generate it."
    }

    [xml]$x = Get-Content $csprojPath
    $name = [System.IO.Path]::GetFileNameWithoutExtension($csprojPath)

    $srcs = @($x.SelectNodes("//*[local-name()='Compile']") | ForEach-Object { $_.GetAttribute('Include') })

    # Sources the csproj does not know about yet, because Unity has not been focused since they were
    # added. Compared on full path so a differently-spelled Include does not smuggle in a duplicate.
    if ($extraSources.Count -gt 0) {
        $known = @{}
        foreach ($s in $srcs) { $known[[System.IO.Path]::GetFullPath((Join-Path $root $s))] = $true }

        foreach ($extra in $extraSources) {
            $fullExtra = [System.IO.Path]::GetFullPath($extra)
            if ($known.ContainsKey($fullExtra)) { continue }
            Write-Host "  + $($fullExtra.Substring($root.Length + 1)) (not in csproj yet)"
            $srcs += $fullExtra
        }
    }
    $hintRefs = @($x.SelectNodes("//*[local-name()='HintPath']") | ForEach-Object { $_.InnerText })
    $projRefs = @($x.SelectNodes("//*[local-name()='ProjectReference']") | ForEach-Object { $_.GetAttribute('Include') })
    $defines = ($x.SelectNodes("//*[local-name()='DefineConstants']") | Select-Object -First 1).InnerText

    # Every ProjectReference has to exist as a built dll before this project can compile against it.
    $projRefDlls = New-Object System.Collections.Generic.List[string]

    foreach ($pr in $projRefs) {
        $prPath = [System.IO.Path]::GetFullPath((Join-Path $root $pr))
        Compile-Project $prPath
        $projRefDlls.Add($built[$prPath])
    }

    # Write-Host rather than Write-Output for our own status lines: it bypasses the success stream
    # entirely, so these survive even if some future caller does pipe this function somewhere. csc's
    # real diagnostics stay on native stdout below, which is what redirects into a log file.
    Write-Host "$name`: $($srcs.Count) sources, $($hintRefs.Count) references, $($projRefs.Count) project references"

    $out = Join-Path $env:TEMP "gmtk-compile-check-$name.dll"

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('-target:library')
    $lines.Add('-langversion:9')
    $lines.Add('-nostdlib+')
    # CS0649/CS0169/CS0414: [SerializeField] fields are assigned by Unity's serializer, which Roslyn
    # cannot see. Suppressed so real diagnostics are not buried.
    $lines.Add('-nowarn:0649,0169,0414')
    $lines.Add("-out:`"$out`"")
    if ($defines) { $lines.Add("-define:$defines") }

    # Skipped when missing, for the same staleness reason as the sources below.
    foreach ($r in $hintRefs) {
        $p = $r
        if (-not [System.IO.Path]::IsPathRooted($p)) { $p = Join-Path $root $p }
        if (-not (Test-Path $p)) { continue }
        $lines.Add("-r:`"$p`"")
    }
    # Every ProjectReference built above, fed back in as a -r:. Assembly-CSharp reaches
    # Assembly-CSharp-firstpass this way, which is where DOTween's UI module extension methods live.
    foreach ($d in $projRefDlls) { $lines.Add("-r:`"$d`"") }
    # Includes out of the csproj are repo-relative; injected extras are already absolute.
    #
    # A missing file is skipped rather than passed to csc. The csproj is gitignored and only rewritten
    # when the Unity Editor is focused, so it lists files DELETED since the last focus just as surely as
    # it omits files added since - and csc turns each one into a CS2001 that buries whatever real
    # diagnostic the run was for. This is the same staleness the extraSources sweep above corrects, in
    # the other direction.
    $stale = 0

    foreach ($s in $srcs) {
        $p = $s
        if (-not [System.IO.Path]::IsPathRooted($p)) { $p = Join-Path $root $p }
        if (-not (Test-Path $p)) { $stale++; continue }
        $lines.Add("`"$p`"")
    }

    if ($stale -gt 0) {
        Write-Host "  - $stale source(s) listed in the csproj no longer exist on disk (skipped)"
    }

    $rsp = Join-Path $env:TEMP "gmtk-compile-check-$name.rsp"
    Set-Content -Path $rsp -Value $lines -Encoding utf8

    # Left to stream to the console rather than captured, and deliberately NOT redirected with 2>&1.
    # Under $ErrorActionPreference = 'Stop', Windows PowerShell 5.1 turns any stderr write by a native
    # command into a terminating error the moment it is merged with 2>&1 - even when that command
    # exits 0. csc puts its CS#### diagnostics on stdout, so that never fires today, but a dotnet
    # launch failure or an SDK warning after a Unity upgrade would have blown the script up with a
    # RemoteException dump instead of a clean COMPILE FAILED - or worse, failed a build that actually
    # succeeded. Unredirected, both streams print and $LASTEXITCODE stays honest.
    & $dotnet $csc.FullName "@$rsp"
    $code = $LASTEXITCODE

    if ($code -ne 0) {
        Write-Host "COMPILE FAILED ($code) in $name"
        exit $code
    }

    [void]$building.Remove($csprojPath)
    $built[$csprojPath] = $out
}

# Runtime .cs under Assets/Scripts that Assembly-CSharp.csproj has not caught up with, for the same
# reason the -IncludeEditor sweep below exists: the csproj is gitignored and only rewritten when the
# Unity Editor is focused, so a script added since the last focus is invisible here - and a check that
# silently skips a file it was asked about is worse than no check. Assets/Scripts/Editor is excluded
# because it compiles into Assembly-CSharp-Editor, not this assembly.
$runtimeSources = @()
$scriptsDir = Join-Path $root 'Assets\Scripts'
$scriptsEditorDir = Join-Path $scriptsDir 'Editor'

if (Test-Path $scriptsDir) {
    $runtimeSources = @(Get-ChildItem -Path $scriptsDir -Recurse -Filter '*.cs' -File |
        Where-Object { -not $_.FullName.StartsWith($scriptsEditorDir, [System.StringComparison]::OrdinalIgnoreCase) } |
        ForEach-Object { $_.FullName })
}

Compile-Project $proj $runtimeSources

if ($IncludeEditor) {
    $editorProj = Join-Path $root 'Assembly-CSharp-Editor.csproj'

    $editorSources = @()
    foreach ($dir in @('Assets\Editor', 'Assets\Scripts\Editor')) {
        $full = Join-Path $root $dir
        if (Test-Path $full) {
            $editorSources += @(Get-ChildItem -Path $full -Recurse -Filter '*.cs' -File | ForEach-Object { $_.FullName })
        }
    }

    Compile-Project $editorProj $editorSources
}

Write-Host "COMPILE OK"
exit 0
